on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
name: Continuous Integration
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 16 ]
    name: Java ${{ matrix.java }}
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: ./mvnw verify
      - name: Upload artefact
        uses: actions/upload-artifact@master
        with:
          name: capfile-java-${{ matrix.java }}.jar
          path: target/capfile.jar
