on: pull_request
name: PR check
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 13 ]
    name: Java ${{ matrix.java }}
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.java }}
      - run: mvn verify
      - name: Upload artefact
        uses: actions/upload-artifact@master
        with:
          name: capfile
          path: target/capfile.jar
